using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using OrderManagement.Api.Extensions;
using OrderManagement.Application.Abstractions.Demo;
using OrderManagement.Application.DTOs.Demo;
using OrderManagement.Domain.Enums;

namespace OrderManagement.Api.Controllers;

[ApiController]
[Authorize(Policy = AuthorizationPolicies.AuthenticatedUser)]
[Route("api/v1/demo")]
public sealed class DemoController : ControllerBase
{
    private readonly IDemoService _demoService;

    public DemoController(IDemoService demoService)
    {
        _demoService = demoService;
    }

    /// <summary>
    /// Demonstrates the concurrent stock deduction scenario (Skenario A).
    /// Two concurrent orders for the same product, each requesting the same quantity.
    /// Only one should succeed when stock is insufficient for both.
    ///
    /// <para>
    /// <b>Layer 1 — Controller:</b> Idempotency-Key is generated by the demo service
    /// (simulating what the client would do). The <c>RequireIdempotencyKeyFilter</c>
    /// is bypassed here because keys are generated internally; the real
    /// <c>OrderService.CreateAsync</c> still uses them for idempotency protection.
    /// </para>
    ///
    /// <para>
    /// <b>Layer 2 — Repository:</b> Inside <c>OrderRepository.CreateAsync</c>,
    /// <c>SELECT ... FOR UPDATE</c> locks the product rows so concurrent transactions
    /// block until the first one commits. Then <c>UPDATE ... WHERE stock &gt;= quantity</c>
    /// ensures the stock check + deduction is atomic.
    /// </para>
    /// </summary>
    [HttpPost("concurrent-stock-deduction")]
    [ProducesResponseType(typeof(ConcurrentStockDeductionResponse), StatusCodes.Status200OK)]
    public async Task<ActionResult<ConcurrentStockDeductionResponse>> ConcurrentStockDeduction(
        [FromBody] ConcurrentStockDeductionRequest request,
        CancellationToken cancellationToken)
    {
        if (request.ProductId == Guid.Empty)
        {
            return BadRequest(new
            {
                error = new
                {
                    code = "VALIDATION_ERROR",
                    message = "ProductId is required."
                }
            });
        }

        if (request.Quantity <= 0)
        {
            return BadRequest(new
            {
                error = new
                {
                    code = "VALIDATION_ERROR",
                    message = "Quantity must be greater than 0."
                }
            });
        }

        if (request.CustomerId == Guid.Empty)
        {
            return BadRequest(new
            {
                error = new
                {
                    code = "VALIDATION_ERROR",
                    message = "CustomerId is required."
                }
            });
        }

        var result = await _demoService.RunConcurrentStockDeductionAsync(request, cancellationToken);

        return Ok(result);
    }
}
